README.md, check-license-compliance.sh, pom.xml, third-party-licenses.sh, travis.sh
Upgrading to parent 45 allows to improve the verification of
license compliance of third-party dependencies.
The new script check-license-compliance.sh fails if a dependency
has a license that is not compatible with SonarSource policy.
See https://xtranet.sonarsource.com/display/DEV/Open+Source+Licenses
for more details.
=> Check license compliance on Travis

its/plugin/src/test/java/com/sonar/python/it/plugin/MetricsTest.java
Due to modules drop in SQ 7.6 this metric computation changed
Dropping asserting completely as it doesn't bring a lot of value while testing plugin behaviour
=> Remove directories number assertion in plugin IT

sslr-python-toolkit/pom.xml, sslr-python-toolkit/src/main/java/org/sonar/python/toolkit/PythonConfigurationModel.java
"sslr-python-toolkit" module does not need to depend on "sonar-plugin-api", so "java.util.logging.Logger" is sufficient for this module.
=> SONARPY-281 Remove slf4j dependency

python-checks/src/main/java/org/sonar/python/checks/PrintStatementUsageCheck.java, python-checks/src/test/java/org/sonar/python/checks/PrintStatementUsageCheckTest.java, python-checks/src/test/resources/checks/printStatementUsage-validpython3.py, python-frontend/pom.xml, python-frontend/src/main/java/org/sonar/python/frontend/PythonParser.java, python-frontend/src/test/java/org/sonar/python/frontend/PythonParserTest.java, sonar-python-plugin/pom.xml, sonar-python-plugin/src/main/java/org/sonar/plugins/python/PythonScanner.java
The other commit comes from #251
=> SONARPY-345 Parser should parse Python3 by default and fallback to Python2

python-checks/src/test/resources/checks/emptyNestedBlock.py
This was fixed by new handling of comment, dedent and newline in strongly typed AST
=> SONARPY-355 add testcase to empty nested block checked.

python-checks/src/main/java/org/sonar/python/checks/hotspots/CsrfDisabledCheck.java, python-checks/src/test/java/org/sonar/python/checks/hotspots/CsrfDisabledCheckTest.java, python-checks/src/test/resources/checks/hotspots/csrfDisabledCheck/django/settings.py, python-checks/src/test/resources/checks/hotspots/csrfDisabledCheck/flask/fixupCsrfInGlobalScope.py, python-checks/src/test/resources/checks/hotspots/csrfDisabledCheck/flask/fixupTestsMoreRobustCSRFProtect.py, python-checks/src/test/resources/checks/hotspots/csrfDisabledCheck/flask/global.py
* add flask_wtf.CSRFProtect to FQNs that deactivate the issue message
* loosen the requirements on csrf.init_app invocations - allow purely lexical matches
* further standardize issue messages
=> minor fixes (flask_wtf.CSRFProtect imports, csrf.init_app for unknown symbols)

python-frontend/src/main/java/org/sonar/python/metrics/FileLinesVisitor.java, python-frontend/src/test/java/org/sonar/python/FileLinesVisitorTest.java, python-frontend/src/test/resources/metrics/file_lines.py
Duplicates #707 to trigger all checks.
=> SONARPY-684 Count module-level docstrings as comments

python-checks/src/main/java/org/sonar/python/checks/ConstantConditionCheck.java, python-checks/src/test/resources/checks/constantCondition.py
Two cases that were specified have been left out:
* Imported names: there are projects which seem to use some imported names as compatibility flags (see example in the test cases). As we have no reliable way to know for any particular symbol, those cases haven't been covered.
* Generator case where a variable is assigned a generator returned through a function. Again, we have no reliable way to ensure the behavior of the function, so it has been flagged as a FN.
=> SONARPY-672 Add missing cases for rule S5797

sonar-python-plugin/src/main/resources/static/documentation.md
Closing tag is already present at the end of the file
=> SONARPY-861 Show 'custom rules' documentation only in SonarQube

python-checks/src/main/java/org/sonar/python/checks/regex/AbstractRegexCheck.java, python-checks/src/test/java/org/sonar/python/checks/regex/AbstractRegexCheckTest.java, python-checks/src/test/resources/checks/regex/abstractRegexCheck.py, python-checks/src/test/resources/checks/regex/abstractRegexCheckCache.py, python-frontend/src/main/java/org/sonar/python/SubscriptionVisitor.java, python-frontend/src/test/java/org/sonar/python/SubscriptionVisitorTest.java
I had to make the regex cache's key also depend on the flags. We didn't have to do that in PHP because the global flags are part of the string literal.
One thing I'm not 100% convinced about yet is that, if we do raise on the value of a variable, we might have raised because of some flags. However, in the location we raise, those flags are not visible. I'm not certain if this will lead to unclear issues. We can go with it now, and adapt if that will be the case.
=> SONARPY-923 Analyze regex in variables whose values we can infer

python-frontend/src/main/java/org/sonar/python/index/DescriptorUtils.java, python-frontend/src/main/java/org/sonar/python/semantic/ProjectLevelSymbolTable.java, python-frontend/src/main/java/org/sonar/python/semantic/Scope.java, python-frontend/src/main/java/org/sonar/python/semantic/SymbolTableBuilder.java, python-frontend/src/main/java/org/sonar/python/semantic/SymbolUtils.java, python-frontend/src/test/java/org/sonar/python/semantic/ClassSymbolImplTest.java, python-frontend/src/test/java/org/sonar/python/semantic/ProjectLevelSymbolTableTest.java, python-frontend/src/test/java/org/sonar/python/types/TypeShedTest.java
Thanks to descriptors, symbols from the project symbol table are always new and shouldn't require any copy logic (`copyWithoutUsage` or `copySymbol`).
This PR also fix a bug when a descriptor within an ambiguous descriptor has a `null` FQN and cannot be retrieved properly by `createdSymbols`.
=> Avoid copying symbols that come from the project table and fix bug for ambiguous descriptors with null FQN

its/ruling/src/test/java/org/sonar/python/it/PythonRulingTest.java
The previous header format used in the ruling test to validate S1451 was using hard-coded `\n` eol characters which were only valid if the analyzed file used unix-like line endings. This caused problem on Windows machines while not being necessary for the test, so I only kept the first line of the header, which is enough for the test.
=> Simplify required header format for S1451 on ruling

its/plugin/it-python-plugin-test/profiles/profile-python-test-rules.xml, its/plugin/it-python-plugin-test/projects/test_code/src/some_code.py, its/plugin/it-python-plugin-test/projects/test_code/tests/test_my_code.py, its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/MetricsTest.java, its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/TestRulesTest.java, its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/Tests.java, python-checks/src/main/java/org/sonar/python/checks/tests/AssertOnTupleLiteralCheck.java, python-checks/src/main/java/org/sonar/python/checks/tests/SkippedTestNoReasonCheck.java, python-checks/src/test/java/org/sonar/python/checks/tests/AssertOnTupleLiteralCheckTest.java, python-checks/src/test/java/org/sonar/python/checks/tests/SkippedTestNoReasonCheckTest.java, python-frontend/src/main/java/org/sonar/plugins/python/api/PythonCheck.java, python-frontend/src/test/java/org/sonar/python/PythonCheckTest.java, sonar-python-plugin/src/main/java/org/sonar/plugins/python/PythonScanner.java, sonar-python-plugin/src/main/java/org/sonar/plugins/python/PythonSensor.java, sonar-python-plugin/src/test/java/org/sonar/plugins/python/PythonSensorTest.java, sonar-python-plugin/src/test/resources/org/sonar/plugins/python/sensor/test_file.py
Some coverage is missing; it will be more convenient to add it when we merge a rule whose scope is `TEST`, such as [SONARPY-763](https://sonarsource.atlassian.net/browse/SONARPY-763) (Note: I believe we should specify explicitly which test rule can or cannot be run on main files, depending on our expectations of risk of FPs).
=> SONARPY-1064 Enable test checks to run on project test files

python-checks/src/main/java/org/sonar/python/checks/cdk/AbstractCdkResourceCheck.java, python-checks/src/main/java/org/sonar/python/checks/cdk/AbstractS3BucketCheck.java, python-checks/src/main/java/org/sonar/python/checks/cdk/CdkPredicate.java, python-checks/src/main/java/org/sonar/python/checks/cdk/CdkUtils.java, python-checks/src/main/java/org/sonar/python/checks/cdk/ClearTextProtocolsCheckPart.java, python-checks/src/main/java/org/sonar/python/checks/cdk/DisabledEFSEncryptionCheck.java, python-checks/src/main/java/org/sonar/python/checks/cdk/DisabledESDomainEncryptionCheck.java, python-checks/src/main/java/org/sonar/python/checks/cdk/DisabledRDSEncryptionCheck.java, python-checks/src/main/java/org/sonar/python/checks/cdk/DisabledSNSTopicEncryptionCheck.java, python-checks/src/main/java/org/sonar/python/checks/cdk/S3BucketBlockPublicAccessCheck.java, python-checks/src/main/java/org/sonar/python/checks/cdk/S3BucketGrantedAccessCheck.java, python-checks/src/main/java/org/sonar/python/checks/cdk/S3BucketServerEncryptionCheck.java, python-checks/src/main/java/org/sonar/python/checks/cdk/S3BucketVersioningCheck.java, python-checks/src/main/java/org/sonar/python/checks/cdk/UnencryptedEbsVolumeCheck.java, python-checks/src/main/java/org/sonar/python/checks/cdk/UnencryptedSageMakerNotebookCheck.java, python-checks/src/main/java/org/sonar/python/checks/cdk/UnencryptedSqsQueueCheck.java, python-checks/src/main/java/org/sonar/python/checks/cdk/WeakSSLProtocolCheckPart.java, python-checks/src/test/resources/checks/cdk/disabledESDomainEncryptionCheck.py
First version, the class `S3BucketGrantedAccessCheck` does not use the class `AbstractS3BucketCheck` properly, so the current adaptation is not really meaningful. Not sure if we can really adapt it as it is really different from other S3Bucket classes and from the intended use of the abstract class.
=> SONARPY-1150 Drop deprecated methods from 'AbstractCdkResourceCheck'

its/ruling/src/test/resources/expected/python-S5655.json, its/ruling/src/test/resources/expected/python-S5717.json, its/ruling/src/test/resources/expected_extended/scikit-learn/python-S5644.json, python-checks/src/test/resources/checks/argumentType.py, python-checks/src/test/resources/checks/incompatibleOperands/arithmetic.py, python-frontend/src/main/java/org/sonar/python/semantic/Scope.java, python-frontend/src/main/java/org/sonar/python/semantic/SymbolImpl.java, python-frontend/src/main/java/org/sonar/python/tree/QualifiedExpressionImpl.java, python-frontend/src/main/java/org/sonar/python/types/InferredTypes.java, python-frontend/src/test/java/org/sonar/python/types/InferredTypesTest.java, python-frontend/src/test/java/org/sonar/python/types/TypeInferenceTest.java
This reverts commit 87248fc71077187aaf7f490214e1205cef775742.
This commit has been reverted because there are some regressions on sonar-security
=> Revert "SONARPY-1165 Infer types of Typeshed class attributes (#1232)"

sonar-python-plugin/src/main/java/org/sonar/plugins/python/indexer/SonarQubePythonIndexer.java
The computation of fully qualified names requires that `projectBaseDirAbsolutePath` is set, so that the base directory of the project is not considered as part of fully qualified names within the project even when containing an `__init__.py` file.
This PR will fix an inconsistency in FQNs computation that may cause NullPointerException in some cases.
=> Compute main files FQNs after setting the project base dir path

python-frontend/src/main/java/org/sonar/plugins/python/api/tree/ExceptClause.java, python-frontend/src/main/java/org/sonar/plugins/python/api/tree/Tree.java, python-frontend/src/main/java/org/sonar/python/api/PythonGrammar.java, python-frontend/src/main/java/org/sonar/python/tree/ExceptClauseImpl.java, python-frontend/src/main/java/org/sonar/python/tree/PythonTreeMaker.java, python-frontend/src/test/java/org/sonar/python/parser/compound/statements/ExceptClauseTest.java, python-frontend/src/test/java/org/sonar/python/parser/compound/statements/TryStatementTest.java, python-frontend/src/test/java/org/sonar/python/tree/PythonTreeMakerTest.java
The * character is already defined in PythonPunctuator as MUL, it does not seems possible to have to Punctuator with the same character, as from my understanding when it generate the AST, it take the first corresponding character as such.
So for now I let it as it and used this MUL punctuator, open for suggestion !
=> SONARPY-1169 Support except* syntax

python-checks/src/main/java/org/sonar/python/checks/ChildAndParentExceptionCaughtCheck.java, python-checks/src/test/resources/checks/childAndParentExceptionCaughtCheck.py
As usual, slightly adapted to make it work with Python 3.11.
Duplicated test code, I didn't normalize the indent of the test file to focus only on real modification, but I can still do it If you think it's a good idea.
=> SONARPY-1183 S5713 (ChildAndParentExceptionCaughtCheck) should report on except*

its/ruling/src/test/java/org/sonar/python/it/PythonPrAnalysisTest.java, python-frontend/src/main/java/org/sonar/python/caching/CacheContextImpl.java, python-frontend/src/test/java/org/sonar/python/caching/CacheContextImplTest.java, sonar-python-plugin/src/test/java/org/sonar/plugins/python/PythonSensorTest.java
Goal is to disable caching for SonarPython 3.21 which will be integrated into SonarQube 9.8 release.
This feature could break SonarSecurity and Dataflow bug detection for Python, since the version of these analyzers to be integrated in 9.8 do not implement the required caching APIs.
=> SONARPY-1222 Disable cache to prepare for SQ 9.8 release

its/ruling/src/test/java/org/sonar/python/it/PythonPrAnalysisTest.java, sonar-python-plugin/pom.xml, sonar-python-plugin/src/main/java/org/sonar/plugins/python/PythonSensor.java, sonar-python-plugin/src/main/java/org/sonar/plugins/python/caching/Caching.java, sonar-python-plugin/src/main/java/org/sonar/plugins/python/indexer/SonarQubePythonIndexer.java, sonar-python-plugin/src/test/java/org/sonar/plugins/python/PythonSensorTest.java, sonar-python-plugin/src/test/java/org/sonar/plugins/python/caching/CachingTest.java, sonar-python-plugin/src/test/java/org/sonar/plugins/python/indexer/SonarQubePythonIndexerTest.java
Two comments on this PR:
* I left the `cacheContext` as a constructor parameter to `SonarQubePythonIndexer` although it is no longer necessary (since it's only built from the `SensorContext` which is now a constructor parameter as well). The reason for that is to not hinder the testability of the `SonarQubePythonIndexer`, in which we currently inject some test cache contexts. I'm not 100% sure it's the right way to do this, though.
* In unit tests, we don't have an implementation version available. I used the `unknown` default value as if it were a valid value. The behavior of the cache versioning itself is tested in the ITs where the implementation version is actually available.
=> SONARPY-1221 Invalidate cache when the analyzer version changes

python-frontend/src/main/java/org/sonar/python/tree/TreeUtils.java, python-frontend/src/test/java/org/sonar/python/semantic/ProjectLevelSymbolTableTest.java
The root cause of this problem is not trivial to fix: our symbol table builder works in two phases: the first records all "write" usages, and the second records all "read" usages. This is because it is possible to have "read" usages appear before the corresponding "write" (e.g, calling a function defined later in the code from another function body).
This leads to an implicit hoisting of symbols which is not always correct. In this case, the class symbol that is being defined ends up being considered as its supertype.
SONARPY-1350 was created to fix this. This PR prevents the stack overflow from happening, but doesn't fix the incorrect semantic resolution.
=> SONARPY-1345 Fix stack overflow when a nested class inherits from a class with the same name

python-checks/src/main/java/org/sonar/python/checks/ComparisonToNoneCheck.java, python-checks/src/test/resources/checks/comparisonToNoneCheck.py, python-frontend/src/main/java/org/sonar/plugins/python/api/types/BuiltinTypes.java
This PR removes some FPs but also adds some FNs.
Because I think we would want to raise an issue on:
```
obj = object()
if obj is not None: pass # Remove this identity check; it will always be True.
```
Is it ok to have a bit more FNs, by assuming that the comparison between object and None is always meaningful?
=> SONARPY-1325 Fix FP on S5727 when annotated return type is object

python-frontend/src/main/java/org/sonar/python/semantic/Scope.java, python-frontend/src/test/java/org/sonar/python/semantic/SymbolTableBuilderTest.java, python-frontend/src/test/resources/semantic/symbols2.py
The missing condition of coverage is an old defensive check. To be honest, I don't remember what it's about but I'd rather just keep it as a defensive check and accept the missing piece of coverage.
=> SONARPY-1384 Ensure submodule imports doesn't prevent parent module import

python-checks/src/main/java/org/sonar/python/checks/SpecialMethodReturnTypeCheck.java, python-checks/src/test/resources/checks/specialMethodReturnTypeCheck.py
This is a minor change to not raise any issues for functions whose name matches one of the special methods but which are not actual methods.
Example:
```python
class C:
def __bool__(self):
return "Hello" # Noncompliant
def __bool__():
return "Hello" # Compliant: This function is not part of a class definition
```
Hence, this fixes potential (albeit very unlikely) FPs
=> SONARPY-1402 Rule S6658: Fix - Raise only for methods

python-frontend/pom.xml, python-frontend/typeshed_serializer/runners/tox_runner.py, python-frontend/typeshed_serializer/tests/runners/test_tox_runner.py
This PR depends on SONARPY-1427
=> SONARPY-1426: Failling Typeshed tests should fail the maven build

python-checks/src/main/resources/org/sonar/l10n/py/rules/python/S935.json
There was an "S" in front of the rule number in the "ruleSpecification" value for the python version of the rule. I.e. "RSPEC-S935" -> "RSPEC-935".
This caused problems with the deployment of the rules marketing website: http://rules.sonarsource.com/
The corresponding change in the rspec repository have already been made, see the following PR: https://github.com/SonarSource/rspec/pull/2895
The changes of this commit have been generated using the rule API.
=> S935: Fix ruleSpecification value in metadata

python-checks/src/test/resources/checks/incompatibleOperands/comparison.py, python-frontend/src/main/java/org/sonar/python/types/InferredTypes.java, python-frontend/src/test/java/org/sonar/python/types/RuntimeTypeTest.java
I did not see a clean and easy way to represent this other than by hardcoding it.
By our definition, a list can be used as a substitute for a tuple and they are therefore compatible types in that regard, as they define the same members.
We know it's actually not the case and I therefore hardcoded that information.
=> SONARPY-1374 Fix FN on S5607: list and tuple are not duck-type compatible

its/ruling/src/test/java/org/sonar/python/it/PythonExtendedRulingTest.java
The initial goal of this ticket was to add an actual Python 3.12 project, or a project for which our new rules could raise issues (such as `mypy`).
However, this is not practical for various reasons:
* Extended ruling currently only raises issues on hardcoded bug rules, which is something that should be revisited (SONARPY-984) (our new rules are code smells)
* Reusing `mypy` would require changing the actual ruling as well, for which there is still an open ticket (SONARPY-1366)
* There are not yet many projects that use the Python 3.12 syntax to be integrated in our ruling tests.
Simply setting one of our existing project as a Python 3.12 project allows us to guarantee analysis performs correctly on such project for a fraction of the cost that would be involved should we want an actual …
=> SONARPY-1523 Configure an extended ruling project as a Python 3.12 project

.cirrus.yml
This PR follows the required changes depicted on [this page](https://xtranet-sonarsource.atlassian.net/wiki/spaces/RE/pages/2931064959/Cirrus+CI+-+How+to+migrate+away+of+GCP+promote+function)
=> SONARPY-1550: Google cloud function for promotion migration

its/ruling/src/test/resources/expected/python-S1172.json, python-checks/src/main/java/org/sonar/python/checks/UnusedFunctionParameterCheck.java, python-checks/src/test/resources/checks/unusedFunctionParameter/unusedFunctionParameter.py
I decided to go for a less aggressive approach than initially  discussed (excluding all methods from this rule). Instead, I decided to:
* Exclude parameter names `event` and `context` that may be required by AWS Lambda.
* Exclude any parameter that is referenced in a string literal or a comment (thus excluding any case of documented unused parameter for overriding purpose as well as anything that may be used through a DSL).
Seeing the results on ruling, this will make us lose some legitimate issues, although I believe the benefit of raising fewer FPs is worth the cost. Despite this change, this rule might still prove problematic and we might want to consider a more aggressive approach later.
=> SONARPY-1563 Fix FPs on S1172 when the parameter is intentionally unused

sonar-python-plugin/src/main/java/org/sonar/plugins/python/PythonSensor.java
DBD is working on support for SonarLint in VSCode. For this purpose, a ProjectSensor needs to be used on the DBD side that depends on the PythonSensor.
PythonSensor is a non-global, non-ProjectSensor.
SonarLintPythonBugDetectionSensor is a ProjectSensor. Based on this
[documentation](https://github.com/SonarSource/sonar-plugin-api/blob/master/docs/influencing-extensions-execution-order.md), they already should be running in order:
> In the Plugin API, there are 3 special extension points:
> * `org.sonar.api.batch.sensor.Sensor`
> * `org.sonar.api.scanner.sensor.ProjectSensor`
> * `org.sonar.api.batch.postjob.PostJob`
> [...]
> In Sonar products, extensions coming from those 3 extension points are executed one after another.
Except perhaps for the `root` module:
> Note that …
=> DBD-673b: PythonSensor is depended upon by SonarLintPythonBugDetectionSensor

python-checks/src/main/java/org/sonar/python/checks/UseOfAnyAsTypeHintCheck.java, python-checks/src/main/java/org/sonar/python/checks/cdk/CdkPredicate.java, python-checks/src/main/java/org/sonar/python/checks/cdk/ClearTextProtocolsCheckPart.java, python-checks/src/main/java/org/sonar/python/checks/django/DjangoReceiverDecoratorCheck.java, python-checks/src/main/java/org/sonar/python/checks/regex/UnusedGroupNamesCheck.java, python-frontend/src/main/java/org/sonar/python/tree/TreeUtils.java, python-frontend/src/test/java/org/sonar/python/tree/PythonTreeMakerMatchStatementTest.java, python-frontend/src/test/java/org/sonar/python/tree/PythonTreeMakerTest.java, python-frontend/src/test/java/org/sonar/python/tree/TreeUtilsTest.java
Due to the fact this API is often used within stream and can be error prone due to the fact it's nullable, I believe it makes sense to have it return an optional instead.
=> Refactor TreeUtils#fullyQualifiedNameFromExpression to return Optional

python-checks/src/test/resources/checks/tests/assertOnDissimilarTypes.py, python-frontend/src/main/java/org/sonar/plugins/python/api/symbols/ClassSymbol.java, python-frontend/src/main/java/org/sonar/python/semantic/ClassSymbolImpl.java, python-frontend/src/main/java/org/sonar/python/types/InferredTypes.java, python-frontend/src/main/java/org/sonar/python/types/RuntimeType.java, python-frontend/src/test/java/org/sonar/python/semantic/ClassSymbolTest.java, python-frontend/src/test/java/org/sonar/python/types/InferredTypesTest.java, python-frontend/src/test/java/org/sonar/python/types/RuntimeTypeTest.java
It seems `RuntimeType#equals` relies on a somewhat loose mechanism to determine that classes are equal, while `equals` is not implemented on `Symbol` level.
I made sure that `metaclass`, `decorator` and type hierarchy resolution status are accounted for when performing this check. 
I think it would be better to have proper `equals` implemented on `ClassSymbol`. However, it seems we actually rely on the loose comparison to implicitly merge almost-identical symbols.  Given we are in the process of refactoring our type inference model and engine, I think the quick-fix makes sense.
=> SONARPY-1747 Fix incorrect type equality when classes vary in metaclass status

python-checks/src/test/resources/checks/nonCallableCalled.py, python-frontend/src/main/java/org/sonar/python/semantic/v2/TypeInferenceV2.java, python-frontend/src/main/java/org/sonar/python/tree/DictionaryLiteralImpl.java, python-frontend/src/main/java/org/sonar/python/tree/SetLiteralImpl.java, python-frontend/src/main/java/org/sonar/python/tree/TupleImpl.java, python-frontend/src/test/java/org/sonar/python/types/v2/ObjectTypeTest.java
Tuple content type is inferred immediately if (and unique) available as tuple are immutables.
This should be seen as a baby step/low-hanging fruit. I'd expect a dedicated effort to tackle any more complex case.
Also, this PR does not deal with display name/representation of those generic types.
Not 100% related to the ticket, but I also took the opportunity to add some missing test for some already covered literal types (str, numeric literals and None).
=> SONARPY-1796 Infer types for set, dict and tuple literals

python-checks/src/main/java/org/sonar/python/checks/NonCallableCalledCheck.java, python-frontend/src/main/java/org/sonar/plugins/python/api/LocationInFile.java, python-frontend/src/main/java/org/sonar/plugins/python/api/PythonVisitorContext.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/ClassTypeBuilder.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/FunctionTypeBuilder.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/SymbolsModuleTypeProvider.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/TypeBuilder.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/TypeInferenceV2.java, python-frontend/src/main/java/org/sonar/python/types/v2/ClassType.java, python-frontend/src/main/java/org/sonar/python/types/v2/FunctionType.java, python-frontend/src/main/java/org/sonar/python/types/v2/ObjectType.java, python-frontend/src/main/java/org/sonar/python/types/v2/PythonType.java, python-frontend/src/test/java/org/sonar/plugins/python/api/PythonVisitorContextTest.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/TypeInferenceV2Test.java, python-frontend/src/test/java/org/sonar/python/types/v2/ClassTypeTest.java, python-frontend/src/test/java/org/sonar/python/types/v2/FunctionTypeTest.java, python-frontend/src/test/java/org/sonar/python/types/v2/ObjectTypeTest.java, python-frontend/src/test/java/org/sonar/python/types/v2/TypesTestUtils.java, python-frontend/src/test/java/org/sonar/python/types/v2/UnionTypeTest.java
To be honest I'm not entirely convinced of the proposed solution and I think you made good points in our discussion, so my goal here is to make sure we have a first baby step that can be used in the `NonCallableCalledCheck` and can be revisited later.
One thing to note is that both `ObjectType` and `ClassType` will point to the definition of the class. To be consistent with the `displayName` implementation, `ClassType#definitionLocation` should probably refer to the definition of `type`, however, I didn't think that makes sense (no such definition could be found anyway) so they both return the location of the class definition instead.
=> SONARPY-1803 Store type definition location in the new type model

its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/BanditReportTest.java, its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/CPDTest.java, its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/CoverageTest.java, its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/CustomRulesTest.java, its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/Flake8ReportTest.java, its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/MetricsTest.java, its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/MypyReportTest.java, its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/NoSonarTest.java, its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/PylintReportTest.java, its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/RuffReportTest.java, its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/TestReportTest.java, its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/TestRulesTest.java, its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/TestsUtils.java, its/ruling/src/test/java/org/sonar/python/it/PythonExtendedRulingTest.java, its/ruling/src/test/java/org/sonar/python/it/PythonPrAnalysisTest.java, its/ruling/src/test/java/org/sonar/python/it/PythonRulingTest.java, its/ruling/src/test/java/org/sonar/python/it/RulingHelper.java, pom.xml
- **Revert "SONARPY-1946 Update scanner version in QA tests (#1836)"**
- **SONARPY-1950 Revert scanner update for ITs and update Orchestrator instead**
=> SONARPY 1950

sonar-python-plugin/src/test/java/org/sonar/plugins/python/IPynbSensorTest.java
- **SONARPY-1987: IPynbSensor should not crash when an error occurs during the parsing of notebooks**
- **SONARPY-2019 Fix NPE for workDir in IPynbSensorTest**
=> SONARPY-2019 Fix NPE for workDir in IPynbSensorTest

python-frontend/src/main/java/org/sonar/python/tree/TokenEnricher.java, python-frontend/src/test/java/org/sonar/python/tree/TokenEnricherTest.java, sonar-python-plugin/src/main/java/org/sonar/plugins/python/IpynbNotebookParser.java
- **SONARPY-2040 Add the sonar.ipynb.file.suffixes property**
- **SONARPY-2051 Single quotes should not count as escaped characters in TokenEnricher**
=> SONARPY-2051 Single quotes should not count as escaped characters in TokenEnricher or IPynbNotebookParser

python-checks/src/test/resources/checks/confusingTypeChecking/nonCallableCalled.py, python-frontend/src/main/java/org/sonar/python/semantic/v2/FunctionTypeBuilder.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/SymbolsModuleTypeProvider.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/types/TrivialTypeInferenceVisitor.java, python-frontend/src/main/java/org/sonar/python/tree/CallExpressionImpl.java, python-frontend/src/main/java/org/sonar/python/types/v2/FunctionType.java, python-frontend/src/main/java/org/sonar/python/types/v2/TypeOrigin.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/TypeInferenceV2Test.java, python-frontend/src/test/java/org/sonar/python/types/v2/FunctionTypeTest.java
It would probably make sense to review this only after SONARPY-2024 is merged, and this PR is rebased.
I have my doubts on the introduction of `TypeOrigin` and would be happy to discuss it. I feel it actually should be included in `TypeSource`, but I felt this would complexify the propagation of type sources, so this solution felt like a simpler step, that we can revisit later.
=> SONARPY-1985 Infer a function return type based on its type hint for locally defined functions

python-checks/src/main/java/org/sonar/python/checks/ExceptionCauseTypeCheck.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/ClassTypeBuilder.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/SymbolsModuleTypeProvider.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/types/TrivialTypeInferenceVisitor.java, python-frontend/src/main/java/org/sonar/python/types/v2/ClassType.java, python-frontend/src/main/java/org/sonar/python/types/v2/LazyTypeWrapper.java, python-frontend/src/main/java/org/sonar/python/types/v2/TypeCheckBuilder.java, python-frontend/src/main/java/org/sonar/python/types/v2/TypeWrapper.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/TypeInferenceV2Test.java, python-frontend/src/test/java/org/sonar/python/types/v2/ClassTypeTest.java, python-frontend/src/test/java/org/sonar/python/types/v2/LazyTypeWrapperTest.java, python-frontend/src/test/java/org/sonar/python/types/v2/TypesTestUtils.java
Notes:
- If this approach of using a `TypeWrapper` is accepted, I think it would make sense to refactor the implementation of `FunctionType#returnType` to use it as well, instead of special casing it. I didn't make this refactor here, to keep this PR simple. However, I think we could then create another ticket/PR to harmonize our implementations.
- I am not fully certain of the terminology around `TypeWrapper`, given we already have `ObjectType#unwrappedType` that serves a different purpose. I wouldn't want this to be confusing, and I am open to suggestions in case another name makes more sense.
- I also have doubts about whether `TypeWrapper` should be exposed in the various APIs (as it currently is) or if it should be made transparent by converting them on the fly to `PythonType.`. I …
=> SONARPY-2114 Migrate S5707 ExceptionCauseTypeCheck to the V2 type model

python-frontend/src/main/java/org/sonar/python/semantic/v2/SymbolsModuleTypeProvider.java, python-frontend/src/main/java/org/sonar/python/types/v2/TypeWrapper.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/TypeInferenceV2Test.java
This pull request includes several changes to improve type handling and testing in the `SymbolsModuleTypeProvider` class and its associated test cases. The changes focus on enhancing the type inference mechanism and refactoring the code for better maintainability.
* [`python-frontend/src/main/java/org/sonar/python/semantic/v2/SymbolsModuleTypeProvider.java`](diffhunk://#diff-768ca79d1818e5bdd6d0645830cbe0a58fb72767a54437eef94bf17face10370R54): Added `TypeWrapper` import to support type wrapping.
* [`python-frontend/src/main/java/org/sonar/python/semantic/v2/SymbolsModuleTypeProvider.java`](diffhunk://#diff-768ca79d1818e5bdd6d0645830cbe0a58fb72767a54437eef94bf17face10370L212-R219): Refactored `convertParameter` method to be non-static and updated it to use `TypeWrapper` for parameter type …
=> SONARPY-2124 Ensure parameters types of imported project functions have their declared type populated.

pom.xml
This update should fix the ws alert without any changes to the outcome of typeshed serialization
=> NO-JIRA: Updated protobuf library version

python-checks/src/test/resources/checks/nonCallableCalled.py, python-checks/src/test/resources/checks/use_of_empty_return_value.py, python-frontend/src/main/java/org/sonar/python/index/FunctionDescriptor.java, python-frontend/src/main/java/org/sonar/python/index/TypeAnnotationDescriptor.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/converter/FunctionDescriptorToPythonTypeConverter.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/converter/TypeAnnotationToPythonTypeConverter.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/typeshed/FunctionSymbolToDescriptorConverter.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/typeshed/TypeSymbolToDescriptorConverter.java, python-frontend/src/main/java/org/sonar/python/types/v2/ClassType.java, python-frontend/src/main/java/org/sonar/python/types/v2/LazyType.java, python-frontend/src/main/java/org/sonar/python/types/v2/LazyUnionType.java, python-frontend/src/main/java/org/sonar/python/types/v2/ResolvableType.java, python-frontend/src/main/java/org/sonar/python/types/v2/TypeWrapper.java, python-frontend/src/test/java/org/sonar/python/index/FunctionDescriptorTest.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/TypeInferenceV2Test.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/converter/DescriptorToPythonTypeConverterTest.java, python-frontend/src/test/java/org/sonar/python/types/v2/LazyUnionTypeTest.java, python-frontend/src/test/java/org/sonar/python/types/v2/ObjectTypeTest.java
This change is a bit rough, in the sense that the `FunctionDescriptor` model can now hold 2 representations of return type. One is `annotatedReturnTypeName`, as a `String`, which historically has been used for locally defined functions. The other is `TypeAnnotationDescriptor` which is a representation that is closer to our protobuf model used for Typeshed symbols. 
Note: only return types are taken care of in the PR. SONARPY-2179 has been created to handle parameters as well.
=> SONARPY-2170 Support detailed return types in Descriptor model

python-frontend/src/main/java/org/sonar/python/semantic/ProjectLevelSymbolTable.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/SymbolsModuleTypeProvider.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/converter/AnyDescriptorToPythonTypeConverter.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/converter/ConversionContext.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/converter/FunctionDescriptorToPythonTypeConverter.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/TypeInferenceV2Test.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/converter/ConversionContextTest.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/converter/DescriptorToPythonTypeConverterTest.java
This pull request introduces several changes to the `python-frontend` module, focusing on enhancing the handling of Python type descriptors and improving type conversion mechanisms. The most important changes include the addition of a new method to retrieve descriptors from a module, updates to the `SymbolsModuleTypeProvider` class to use different type converters, and modifications to the `AnyDescriptorToPythonTypeConverter` class to handle type origins.
* [`python-frontend/src/main/java/org/sonar/python/semantic/ProjectLevelSymbolTable.java`](diffhunk://#diff-b7ec63b867f8e4e30a2a2b2bc9d6f30cc63a272de1ec7d2d6795323270764a18R167-R171): Added a new method `getDescriptorsFromModule` to retrieve descriptors from a module.
* [`python-frontend/src/main/java/org/sonar/python/semantic/v2/SymbolsM …
=> SONARPY-2110 Make the ProjectLevelSymbolTable return the Descriptor model instead of the v1 Symbol model

python-checks/src/main/java/org/sonar/python/checks/IgnoredPureOperationsCheck.java, python-checks/src/test/resources/checks/ignoredPureOperations.py, python-frontend/src/main/java/org/sonar/python/types/v2/TypeCheckBuilder.java, python-frontend/src/test/java/org/sonar/python/types/v2/TypeCheckerTest.java, python-frontend/src/test/java/org/sonar/python/types/v2/TypesTestUtils.java
Note: this PR includes two tickets (SONARPY-2203 and its prerequisite, SONARPY-2201) that can actually be reviewed independently. The limitation in re-exported stub symbols (e.g `flask.Response`) will be tackled in SONARPY-2209.
=> SONARPY-2203 Migrate S2201 IgnoredPureOperationsCheck to the new type model

python-checks/src/main/java/org/sonar/python/checks/IgnoredPureOperationsCheck.java, python-checks/src/test/resources/checks/ignoredPureOperations.py, python-frontend/src/main/java/org/sonar/python/types/v2/TypeCheckBuilder.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/ProjectLevelTypeTableTest.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/TypeCheckerBuilderTest.java, python-frontend/src/test/java/org/sonar/python/types/v2/TypeCheckerTest.java
This is admittedly a very naive approach to fix this FP.
However, I believe that this deserves a broader discussion, considering SONARPY-2013 to allow for easier manipulation of type predicates.
I also considered adding a proper `PythonType#kind` API to avoid checking for instances. However, I feel this can still be done later if the need proves real.
=> SONARPY-2229 Fix FP on S2201 when instantiating the result of a type call

python-frontend/src/main/java/org/sonar/python/semantic/v2/TypeInferenceV2.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/TypeInferenceV2Test.java
[SONARPY-2215](https://sonarsource.atlassian.net/browse/SONARPY-2215)
The CFG is invalid when the control flow structures produce an invalid program. They would result in an exception being raised, which means no symbol or type will be exported in this case.
[SONARPY-2215]: https://sonarsource.atlassian.net/browse/SONARPY-2215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2215 Document absence of types when CFG is invalid

python-frontend/src/main/java/org/sonar/python/index/DescriptorUtils.java, python-frontend/src/test/java/org/sonar/python/semantic/ProjectLevelSymbolTableTest.java
[SONARPY-2249](https://sonarsource.atlassian.net/browse/SONARPY-2249)
[SONARPY-2249]: https://sonarsource.atlassian.net/browse/SONARPY-2249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2249 Fix descriptor to symbol conversion when an ambiguous descriptor has multiple candidates having the same fully qualified name

python-frontend/src/main/java/org/sonar/python/semantic/v2/converter/VariableDescriptorToPythonTypeConverter.java, python-frontend/src/test/java/org/sonar/python/types/v2/UnresolvedImportTypeTest.java
[SONARPY-21194](https://sonarsource.atlassian.net/browse/SONARPY-21194)
=> SONARPY-2194 Prevent the creation of ObjectType[UnknownType] when converting VariableDescriptor

python-frontend/src/main/java/org/sonar/python/index/VariableDescriptor.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/ProjectLevelTypeTable.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/converter/VariableDescriptorToPythonTypeConverter.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/typeshed/VarSymbolToDescriptorConverter.java, python-frontend/src/main/java/org/sonar/python/types/v2/LazyTypeWrapper.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/ProjectLevelTypeTableTest.java
[SONARPY-2242](https://sonarsource.atlassian.net/browse/SONARPY-2242)
[SONARPY-2242]: https://sonarsource.atlassian.net/browse/SONARPY-2242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2242 TypeInferenceV2 should resolve stubs with variable descriptors pointing to submodules

python-frontend/src/main/java/org/sonar/python/semantic/v2/types/TrivialTypeInferenceVisitor.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/TypeInferenceV2Test.java
[SONARPY-2245](https://sonarsource.atlassian.net/browse/SONARPY-2245)
[SONARPY-2245]: https://sonarsource.atlassian.net/browse/SONARPY-2245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2245 Fix resolving type for a name if its type is UnresolvedImportType

python-checks/src/main/java/org/sonar/python/checks/PandasReadNoDataTypeCheck.java
[SONARPY-2207](https://sonarsource.atlassian.net/browse/SONARPY-2207)
[SONARPY-2207]: https://sonarsource.atlassian.net/browse/SONARPY-2207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2207 Migrate S6740 PandasReadNoDataTypeCheck to the new type model

python-frontend/src/main/java/org/sonar/python/semantic/v2/TypeInferenceV2.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/TypeInferenceV2Test.java
[SONARPY-2261](https://sonarsource.atlassian.net/browse/SONARPY-2261)
[SONARPY-2261]: https://sonarsource.atlassian.net/browse/SONARPY-2261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2261 get rid of TypeInferenceV2.typesBySymbol field

python-frontend/src/main/java/org/sonar/python/semantic/v2/BasicTypeTable.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/FunctionTypeBuilder.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/LazyTypesContext.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/ProjectLevelTypeTable.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/TypeInferenceV2.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/TypeTable.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/types/FlowSensitiveTypeInference.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/types/IsInstanceVisitor.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/types/TrivialTypeInferenceVisitor.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/BasicTypeTableTest.java, python-frontend/src/test/java/org/sonar/python/types/v2/TypesTestUtils.java
[SONARPY-2262](https://sonarsource.atlassian.net/browse/SONARPY-2262)
[SONARPY-2262]: https://sonarsource.atlassian.net/browse/SONARPY-2262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2262 Introduce the TypesTable interface

python-checks/src/main/java/org/sonar/python/checks/IdentityComparisonWithCachedTypesCheck.java, python-checks/src/test/resources/checks/identityComparisonWithCachedTypes.py, python-frontend/src/main/java/org/sonar/plugins/python/api/tree/Name.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/types/TrivialTypeInferenceVisitor.java, python-frontend/src/main/java/org/sonar/python/tree/UnaryExpressionImpl.java, python-frontend/src/main/java/org/sonar/python/types/v2/TypeCheckBuilder.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/SymbolTableBuilderV2Test.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/TypeInferenceV2Test.java
[SONARPY-2204](https://sonarsource.atlassian.net/browse/SONARPY-2204)
Part of 
[SONARPY-2204]: https://sonarsource.atlassian.net/browse/SONARPY-2204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2204 Migrate S5795 IdentityComparisonWithCachedTypesCheck to the new type model

.cirrus.star, .cirrus.yml
[SONARPY-2282](https://sonarsource.atlassian.net/browse/SONARPY-2282)
[SONARPY-2282]: https://sonarsource.atlassian.net/browse/SONARPY-2282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2282 Update Cirrus modules to v3

python-checks/src/main/java/org/sonar/python/checks/IdentityComparisonWithCachedTypesCheck.java, python-checks/src/test/resources/checks/identityComparisonWithCachedTypes.py, python-frontend/src/main/java/org/sonar/python/types/v2/TypeCheckBuilder.java, python-frontend/src/test/java/org/sonar/python/types/v2/TypeCheckerTest.java
[SONARPY-2288](https://sonarsource.atlassian.net/browse/SONARPY-2288)
Part of 
[SONARPY-2288]: https://sonarsource.atlassian.net/browse/SONARPY-2288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2288 Fix FP on S5795 when checking if type is unsuitable

python-checks/src/test/resources/checks/argumentNumber.py, python-checks/src/test/resources/checks/argumentNumberImported.py, python-checks/src/test/resources/checks/argumentNumberWithImport.py, python-frontend/src/main/java/org/sonar/python/semantic/v2/converter/PythonTypeToDescriptorConverter.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/converter/PythonTypeToDescriptorConverterTest.java
[SONARPY-2276](https://sonarsource.atlassian.net/browse/SONARPY-2276)
[SONARPY-2276]: https://sonarsource.atlassian.net/browse/SONARPY-2276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
SONARPY-2285 has been created to handle bound/unbound methods in a more deliberate way. For now, we just ignore them when handling with re-exports.
It is to be noted that S930 has not been migrated to the new type model yet (only the cross-file analysis was impacted through descriptors). I've still added tests to document the current behavior (no issues raised on bound/unbound methods assigned to variables) that hopefully will help avoid problems when performing the migration.
Ruling tests are still red, due to some other yet unfixed issues.
Note: I suggest …
=> SONARPY-2276 Fix FPs on S930 when an object method is assigned to a variable

python-checks/src/test/resources/checks/identityComparisonWithCachedTypes.py
[SONARPY-2298](https://sonarsource.atlassian.net/browse/SONARPY-2298)
[SONARPY-2298]: https://sonarsource.atlassian.net/browse/SONARPY-2298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2298 document new issues in S5795 stemming from better type resolution

python-checks/src/main/java/org/sonar/python/checks/ChangeMethodContractCheck.java, python-checks/src/test/resources/checks/changeMethodContract.py, python-frontend/src/main/java/org/sonar/python/semantic/v2/converter/FunctionDescriptorToPythonTypeConverter.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/converter/PythonTypeToDescriptorConverter.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/ProjectLevelTypeTableTest.java, python-frontend/src/test/java/org/sonar/python/types/v2/FunctionTypeTest.java
[SONARPY-2290](https://sonarsource.atlassian.net/browse/SONARPY-2290)
[SONARPY-2290]: https://sonarsource.atlassian.net/browse/SONARPY-2290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2290 Support decorators for FunctionType to descriptors converter

python-checks/src/test/resources/checks/nonCallableCalledImported.py, python-checks/src/test/resources/checks/nonCallableCalledImporter.py
[SONARPY-2255](https://sonarsource.atlassian.net/browse/SONARPY-2255)
[SONARPY-2255]: https://sonarsource.atlassian.net/browse/SONARPY-2255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2255 add tests for S5756 on aliased classes

python-checks/src/test/java/org/sonar/python/checks/InconsistentTypeHintCheckTest.java, python-checks/src/test/resources/checks/inconsistentTypeHint.py, python-checks/src/test/resources/checks/inconsistentTypeHintImported.py
[SONARPY-2315](https://sonarsource.atlassian.net/browse/SONARPY-2315)
[SONARPY-2315]: https://sonarsource.atlassian.net/browse/SONARPY-2315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2315 Add unit test case on S5890 when annotated type is imported and has field members only

python-checks/src/test/java/org/sonar/python/checks/FunctionReturnTypeCheckTest.java, python-checks/src/test/resources/checks/functionReturnTypeImported.py, python-checks/src/test/resources/checks/functionReturnTypeImporting.py
[SONARPY-2319](https://sonarsource.atlassian.net/browse/SONARPY-2319)
[SONARPY-2319]: https://sonarsource.atlassian.net/browse/SONARPY-2319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2319 Add unit test case on S5886 when annotated return type is imported and has fields members only

python-checks/src/test/resources/checks/useOfAnyAsTypeHintCheck/useOfAnyAsTypeHintImporting.py, python-frontend/src/main/java/org/sonar/python/index/ClassDescriptor.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/converter/PythonTypeToDescriptorConverter.java, python-frontend/src/test/java/org/sonar/python/semantic/ProjectLevelSymbolTableTest.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/converter/PythonTypeToDescriptorConverterTest.java
[SONARPY-2331](https://sonarsource.atlassian.net/browse/SONARPY-2331)
[SONARPY-2331]: https://sonarsource.atlassian.net/browse/SONARPY-2331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2331 Implement setting metaclassFQN field for ClassType to ClassDescriptor conversion

python-checks/src/test/java/org/sonar/python/checks/hotspots/UnsafeHttpMethodsCheckTest.java, python-checks/src/test/resources/checks/hotspots/unsafeHttpMethods/django/views.py, python-checks/src/test/resources/checks/hotspots/unsafeHttpMethods/django/views_and_urls_same_file.py, python-frontend/src/test/java/org/sonar/python/semantic/ProjectLevelSymbolTableTest.java
[SONARPY-2324](https://sonarsource.atlassian.net/browse/SONARPY-2324)
[SONARPY-2324]: https://sonarsource.atlassian.net/browse/SONARPY-2324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2324 Document missing Django views due to missing resolution of self members

python-frontend/src/main/java/org/sonar/python/semantic/v2/converter/PythonTypeToDescriptorConverter.java, python-frontend/src/test/java/org/sonar/python/semantic/ProjectLevelSymbolTableTest.java
[SONARPY-2342](https://sonarsource.atlassian.net/browse/SONARPY-2342)
[SONARPY-2342]: https://sonarsource.atlassian.net/browse/SONARPY-2342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2342 Fix NPE when metaclassFQN resolved to null during a PythonType to Descriptor conversion

python-frontend/src/main/java/org/sonar/plugins/python/api/PythonVersionUtils.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/typeshed/ProtoUtils.java, python-frontend/src/main/java/org/sonar/python/types/TypeShed.java, python-frontend/src/test/java/org/sonar/plugins/python/api/PythonVersionUtilsTest.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/typeshed/ClassSymbolToDescriptorConverterTest.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/typeshed/ModuleSymbolToDescriptorConverterTest.java, python-frontend/src/test/java/org/sonar/python/types/TypeShedTest.java
[SONARPY-2326](https://sonarsource.atlassian.net/browse/SONARPY-2326)
[SONARPY-2326]: https://sonarsource.atlassian.net/browse/SONARPY-2326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2326 Add Version 3.13 as supported version of Python

python-checks/src/test/java/org/sonar/python/checks/UnusedFunctionParameterCheckTest.java, python-checks/src/test/resources/checks/unusedFunctionParameter/unusedFunctionParameterImport.py, python-checks/src/test/resources/checks/unusedFunctionParameter/unusedFunctionParameterImported.py
[SONARPY-2345](https://sonarsource.atlassian.net/browse/SONARPY-2345)
Part of 
[SONARPY-2345]: https://sonarsource.atlassian.net/browse/SONARPY-2345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2345 Document new S1172 FN when super class is ambiguous

python-frontend/src/main/java/org/sonar/python/index/ClassDescriptor.java, python-frontend/src/main/java/org/sonar/python/index/DescriptorsToProtobuf.java, python-frontend/src/main/java/org/sonar/python/index/FunctionDescriptor.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/ClassTypeBuilder.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/converter/ClassDescriptorToPythonTypeConverter.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/converter/PythonTypeToDescriptorConverter.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/types/TrivialTypeInferenceVisitor.java, python-frontend/src/main/java/org/sonar/python/types/v2/ClassType.java, python-frontend/src/main/protobuf/descriptors.proto, python-frontend/src/test/java/org/sonar/python/PythonTestUtils.java, python-frontend/src/test/java/org/sonar/python/index/AmbiguousDescriptorTest.java, python-frontend/src/test/java/org/sonar/python/index/ClassDescriptorTest.java, python-frontend/src/test/java/org/sonar/python/index/FunctionDescriptorTest.java, python-frontend/src/test/java/org/sonar/python/index/VariableDescriptorTest.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/ProjectLevelTypeTableTest.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/TypeCheckerBuilderTest.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/converter/DescriptorToPythonTypeConverterTest.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/converter/PythonTypeToDescriptorConverterTest.java, python-frontend/src/test/java/org/sonar/python/types/TypeInferenceTest.java, python-frontend/src/test/java/org/sonar/python/types/v2/ClassTypeTest.java, python-frontend/src/test/java/org/sonar/python/types/v2/ModuleTypeTest.java, python-frontend/src/test/java/org/sonar/python/types/v2/ObjectTypeTest.java, python-frontend/src/test/java/org/sonar/python/types/v2/TypesTestUtils.java, python-frontend/src/test/java/org/sonar/python/types/v2/UnionTypeTest.java
[SONARPY-2339](https://sonarsource.atlassian.net/browse/SONARPY-2339)
Following this PR, there are possible null arguments to `ClassDescriptor#fullQualifiedName` and `FunctionDescriptor#fullQualifiedName` in `DescriptorUtils`. These methods are no longer used in production code, and are only used in tests (mostly in `ProjectLevelSymbolTableTest` through `ProjectLevelSymbolTable#from`). [SONARPY-2346](https://sonarsource.atlassian.net/browse/SONARPY-2346) has been created to handle this.
[SONARPY-2339]: https://sonarsource.atlassian.net/browse/SONARPY-2339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SONARPY-2346]: https://sonarsource.atlassian.net/browse/SONARPY-2346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0a …
=> SONARPY-2336 Ensure ClassDescriptor and FunctionDescriptor fullyQualifiedName are not nullable

python-checks/src/test/resources/checks/tests/assertOnDissimilarTypes.py
[SONARPY-2353](https://sonarsource.atlassian.net/browse/SONARPY-2353)
Part of 
[SONARPY-2353]: https://sonarsource.atlassian.net/browse/SONARPY-2353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2353 Improve the reproducer of the S5845 FP when comparing enum objects with types

python-checks/src/test/resources/checks/functionReturnTypeImporting.py, python-checks/src/test/resources/checks/inconsistentTypeHint.py, python-frontend/src/main/java/org/sonar/python/index/DescriptorUtils.java, python-frontend/src/main/java/org/sonar/python/semantic/SymbolImpl.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/converter/PythonTypeToDescriptorConverter.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/types/TrivialTypeInferenceVisitor.java, python-frontend/src/test/java/org/sonar/python/semantic/SymbolImplTest.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/TypeInferenceV2Test.java
[SONARPY-2316](https://sonarsource.atlassian.net/browse/SONARPY-2316)
[SONARPY-2316]: https://sonarsource.atlassian.net/browse/SONARPY-2316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2316 Resolve field members of a ClassType

python-checks/src/test/resources/checks/argumentType.py
[SONARPY-2360](https://sonarsource.atlassian.net/browse/SONARPY-2360)
[SONARPY-2360]: https://sonarsource.atlassian.net/browse/SONARPY-2360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2360 Add unit test case on S5655 when compared types has decorators

python-frontend/src/main/java/org/sonar/python/semantic/v2/types/TrivialTypeInferenceVisitor.java, python-frontend/src/main/java/org/sonar/python/tree/TreeUtils.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/TypeInferenceV2Test.java, python-frontend/src/test/java/org/sonar/python/tree/TreeUtilsTest.java
[SONARPY-2310](https://sonarsource.atlassian.net/browse/SONARPY-2310)
[SONARPY-2310]: https://sonarsource.atlassian.net/browse/SONARPY-2310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2310: Partly support wildcard import

python-checks/src/test/resources/checks/tests/assertOnDissimilarTypes.py, python-frontend/src/main/java/org/sonar/python/types/RuntimeType.java, python-frontend/src/test/java/org/sonar/python/types/RuntimeTypeTest.java
[SONARPY-2332](https://sonarsource.atlassian.net/browse/SONARPY-2332)
Part of 
[SONARPY-2332]: https://sonarsource.atlassian.net/browse/SONARPY-2332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2332 Fix FP on S5845 when comparing enum objects with types

python-frontend/src/test/java/org/sonar/python/semantic/v2/ProjectLevelTypeTableTest.java
[SONARPY-2365](https://sonarsource.atlassian.net/browse/SONARPY-2365)
Part of 
[SONARPY-2365]: https://sonarsource.atlassian.net/browse/SONARPY-2365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2365 Fix quality gate issues for ProjectLevelTypeTableTest

python-checks/src/test/resources/checks/useOfAnyAsTypeHintCheck/useOfAnyAsTypeHint.py, python-checks/src/test/resources/checks/useOfAnyAsTypeHintCheck/useOfAnyAsTypeHintImported.py, python-checks/src/test/resources/checks/useOfAnyAsTypeHintCheck/useOfAnyAsTypeHintImporting.py
[SONARPY-2362](https://sonarsource.atlassian.net/browse/SONARPY-2362)
[SONARPY-2362]: https://sonarsource.atlassian.net/browse/SONARPY-2362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2362 Document no issue on S6542 when inheriting from annotated class member

python-checks/src/test/resources/checks/unusedFunctionParameter/unusedFunctionParameter.py, python-checks/src/test/resources/checks/unusedFunctionParameter/unusedFunctionParameterImport.py, python-checks/src/test/resources/checks/unusedFunctionParameter/unusedFunctionParameterImported.py
[SONARPY-2363](https://sonarsource.atlassian.net/browse/SONARPY-2363)
[SONARPY-2363]: https://sonarsource.atlassian.net/browse/SONARPY-2363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2363 Document no issue on S1172 when inheriting from annotated class member

python-checks/src/main/resources/org/sonar/l10n/py/rules/python/S6554.html, python-checks/src/main/resources/org/sonar/l10n/py/rules/python/S6662.html, python-checks/src/main/resources/org/sonar/l10n/py/rules/python/S6663.html, sonarpedia.json
[SONARPY-2372](https://sonarsource.atlassian.net/browse/SONARPY-2372)
Part of MMF-3945
[SONARPY-2372]: https://sonarsource.atlassian.net/browse/SONARPY-2372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2372 rule-api update

.github/workflows/mark-prs-stale.yml
[SONARPY-2388](https://sonarsource.atlassian.net/browse/SONARPY-2388)
[SONARPY-2388]: https://sonarsource.atlassian.net/browse/SONARPY-2388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2388 Add new GitHub action for stale PRs

renovate.json
[SONARPY-2395](https://sonarsource.atlassian.net/browse/SONARPY-2395)
[SONARPY-2395]: https://sonarsource.atlassian.net/browse/SONARPY-2395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2395 Split the protobuf dependency from the rest to avoid breaking the build of "update all dependencies"

its/ruling/src/test/java/org/sonar/python/it/PythonPrAnalysisTest.java, its/ruling/src/test/java/org/sonar/python/it/RulingHelper.java, pom.xml
[SONARPY-2405](https://sonarsource.atlassian.net/browse/SONARPY-2405)
[SONARPY-2405]: https://sonarsource.atlassian.net/browse/SONARPY-2405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2405 Update Orchestrator to version 5.1

python-frontend/src/main/java/org/sonar/python/TestPythonVisitorRunner.java, python-frontend/src/main/java/org/sonar/python/index/DescriptorUtils.java, python-frontend/src/main/java/org/sonar/python/semantic/ProjectLevelSymbolTable.java, python-frontend/src/test/java/org/sonar/plugins/python/api/PythonVisitorContextTest.java, python-frontend/src/test/java/org/sonar/python/index/AmbiguousDescriptorTest.java, python-frontend/src/test/java/org/sonar/python/semantic/ProjectLevelSymbolTableTest.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/ProjectLevelTypeTableTest.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/TypeInferenceV2Test.java, python-frontend/src/test/java/org/sonar/python/types/v2/TypeCheckerTest.java, sonar-python-plugin/src/main/java/org/sonar/plugins/python/indexer/PythonIndexer.java
[SONARPY-2394](https://sonarsource.atlassian.net/browse/SONARPY-2394)
- **SONARPY-2346 Remove usage of old ProjectLevelSymbolTable#from using V1 symbols**
- **Cleanup DescriptorUtils**
[SONARPY-2394]: https://sonarsource.atlassian.net/browse/SONARPY-2394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2346 Remove usage of old ProjectLevelSymbolTable#from using V1 symbols

python-frontend/src/main/java/org/sonar/python/semantic/v2/types/AstBasedTypeInference.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/types/TrivialTypePropagationVisitor.java, python-frontend/src/main/java/org/sonar/python/semantic/v2/types/TypeDependenciesCalculator.java, python-frontend/src/main/java/org/sonar/python/tree/BinaryExpressionImpl.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/TypeInferenceV2Test.java, python-frontend/src/test/java/org/sonar/python/semantic/v2/types/TypeDependenciesCalculatorTest.java
[SONARPY-2366](https://sonarsource.atlassian.net/browse/SONARPY-2366)
[SONARPY-2366]: https://sonarsource.atlassian.net/browse/SONARPY-2366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2366 Propagate binary expressions of the same type

its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/MetricsTest.java
[SONARPY-2419](https://sonarsource.atlassian.net/browse/SONARPY-2419)
[SONARPY-2419]: https://sonarsource.atlassian.net/browse/SONARPY-2419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2419 Update MetricsTest to stop asserting on deprecated metrics

python-checks/src/main/java/org/sonar/python/checks/FloatingPointEqualityCheck.java, python-checks/src/main/java/org/sonar/python/checks/MissingDocstringCheck.java, python-checks/src/main/java/org/sonar/python/checks/NeedlessPassCheck.java, python-checks/src/main/java/org/sonar/python/checks/TrailingCommentCheck.java, python-checks/src/main/java/org/sonar/python/checks/TrailingWhitespaceCheck.java, python-frontend/src/main/java/org/sonar/plugins/python/api/PythonLine.java, python-frontend/src/main/java/org/sonar/python/metrics/FileLinesVisitor.java, python-frontend/src/main/java/org/sonar/python/quickfix/TextEditUtils.java, python-frontend/src/main/java/org/sonar/python/tree/TokenImpl.java, python-frontend/src/test/java/org/sonar/python/quickfix/TextEditUtilsTest.java
[SONARPY-2407](https://sonarsource.atlassian.net/browse/SONARPY-2407)
[SONARPY-2407]: https://sonarsource.atlassian.net/browse/SONARPY-2407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2407 Refactor Token#line and pythonLine to avoid mixing the two

python-frontend/src/main/java/org/sonar/python/types/v2/LazyUnionType.java, python-frontend/src/test/java/org/sonar/python/types/v2/LazyUnionTypeTest.java
[SONARPY-2266](https://sonarsource.atlassian.net/browse/SONARPY-2266)
[SONARPY-2266]: https://sonarsource.atlassian.net/browse/SONARPY-2266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2266 TypeAnnotationToPythonTypeConverter creates nested LazyUnionType

python-frontend/src/main/java/org/sonar/python/tree/TreeUtils.java
[SONARPY-2420](https://sonarsource.atlassian.net/browse/SONARPY-2420)
It solved the crash locally for me, I can't test this because we can't really analyze notebooks in tests without some more refactoring
[SONARPY-2420]: https://sonarsource.atlassian.net/browse/SONARPY-2420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2420 Fix crash because of mismatch between line and pythonLine

python-frontend/src/main/java/org/sonar/python/semantic/v2/converter/AliasDescriptorToPythonTypeConverter.java, python-frontend/src/test/java/org/sonar/python/types/v2/TypeCheckerTest.java
[SONARPY-2424](https://sonarsource.atlassian.net/browse/SONARPY-2424)
[SONARPY-2424]: https://sonarsource.atlassian.net/browse/SONARPY-2424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2424 Document limitation on AliasDescriptor to PythonType conversion

its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/MetricsTest.java
[SONARPY-2463](https://sonarsource.atlassian.net/browse/SONARPY-2463)
This PR removes the failing test, probably due to the change made in SONAR-22876
[SONARPY-2463]: https://sonarsource.atlassian.net/browse/SONARPY-2463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2463: Fix plugin_qa task

python-frontend/src/main/java/org/sonar/python/semantic/ProjectLevelSymbolTable.java, python-frontend/src/test/java/org/sonar/python/semantic/ProjectLevelSymbolTableTest.java, sonar-python-plugin/src/test/java/org/sonar/plugins/python/PythonSensorTest.java
[SONARPY-2467](https://sonarsource.atlassian.net/browse/SONARPY-2467)
This change avoids recreating the same `TypeCheckBuilder` object repeatedly when performing the Django views visit. Instead, it uses only one for each file.
This implies that we're going to load Typeshed stubs for Django on all files, even if they don't contain `CalleExpression`. While this implication should have no real-world impact, this is what changes some of the project level symbol table and sensor tests 
[SONARPY-2467]: https://sonarsource.atlassian.net/browse/SONARPY-2467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2467 Fix performance bottleneck of GlobalSymbolComputation due to DjangoViewsVisitor

.cirrus.yml
[SONARPY-2461](https://sonarsource.atlassian.net/browse/SONARPY-2461)
[SONARPY-2461]: https://sonarsource.atlassian.net/browse/SONARPY-2461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2461: Fix build_win task cache

wss-unified-agent.config
[SONARPY-2438](https://sonarsource.atlassian.net/browse/SONARPY-2438)
[SONARPY-2438]: https://sonarsource.atlassian.net/browse/SONARPY-2438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2438 Exclude the typeshed serializer from the Mend scan

pom.xml, sonar-python-plugin/src/main/java/org/sonar/plugins/python/IPynbSensor.java, sonar-python-plugin/src/main/java/org/sonar/plugins/python/PythonScanner.java, sonar-python-plugin/src/main/java/org/sonar/plugins/python/SensorTelemetryStorage.java, sonar-python-plugin/src/main/java/org/sonar/plugins/python/TelemetryMetricKey.java, sonar-python-plugin/src/test/java/org/sonar/plugins/python/IPynbSensorTest.java, sonar-python-plugin/src/test/java/org/sonar/plugins/python/SensorTelemetryStorageTest.java
[SONARPY-2451](https://sonarsource.atlassian.net/browse/SONARPY-2451)
SONARPY-2459
[SONARPY-2451]: https://sonarsource.atlassian.net/browse/SONARPY-2451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2451 SONARPY-2459 SONARPY-2464 Collect data for the Jupyter notebooks

sonar-python-plugin/src/main/java/org/sonar/plugins/python/IPynbSensor.java, sonar-python-plugin/src/main/java/org/sonar/plugins/python/PythonSensor.java, sonar-python-plugin/src/main/java/org/sonar/plugins/python/SensorTelemetryStorage.java, sonar-python-plugin/src/main/java/org/sonar/plugins/python/TelemetryMetricKey.java, sonar-python-plugin/src/test/java/org/sonar/plugins/python/PythonSensorTest.java
[SONARPY-2457](https://sonarsource.atlassian.net/browse/SONARPY-2457)
[SONARPY-2457]: https://sonarsource.atlassian.net/browse/SONARPY-2457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2457 Collect data for the Python version

sonar-python-plugin/src/main/java/org/sonar/plugins/python/IPynbSensor.java, sonar-python-plugin/src/main/java/org/sonar/plugins/python/PythonScanner.java, sonar-python-plugin/src/main/java/org/sonar/plugins/python/PythonSensor.java, sonar-python-plugin/src/main/java/org/sonar/plugins/python/SensorTelemetryStorage.java, sonar-python-plugin/src/main/java/org/sonar/plugins/python/TelemetryMetricKey.java, sonar-python-plugin/src/test/java/org/sonar/plugins/python/PythonSensorTest.java, sonar-python-plugin/src/test/resources/org/sonar/plugins/python/sensor/databricks.py
[SONARPY-2477](https://sonarsource.atlassian.net/browse/SONARPY-2477)
[SONARPY-2477]: https://sonarsource.atlassian.net/browse/SONARPY-2477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARPY-2477 Collect data for Databricks notebooks

.cirrus.yml, python-commons/src/main/java/org/sonar/plugins/python/PythonExtensions.java
SONARPY-2538
This reverts commit cb9d60f0b74ffb4085d9847a582cc708e19a22d9.
=> SONARPY-2538 Revert "SONARPY-2506 Remove use of deprecated qualifiers"
