- python-checks/src/main/java/org/sonar/python/checks/TrailingWhitespaceCheck.java
* Since we are using Java 7, use try-with-resources.
* Only read line by line instead of swallowing all lines at once.
* Use JSR 203.
* Use a Matcher and .find() instead of trying to .matches() the whole line.
> TrailingWhitespaceCheck: improve

- its/plugin/src/test/java/com/sonar/python/it/plugin/PylintReportTest.java
- its/plugin/src/test/java/com/sonar/python/it/plugin/Tests.java
- its/plugin/src/test/java/com/sonar/python/it/plugin/XPathRuleTest.java
Replace usage of api/rules/app by api/qualityprofiles/search
Replace of old ws client by latest one
> Remove usage of internal api/rules/app WS

- python-checks/src/main/java/org/sonar/python/checks/CognitiveComplexityFunctionCheck.java
- python-checks/src/test/resources/checks/cognitiveComplexityFunction.py
- python-checks/src/test/resources/checks/cognitiveComplexityFunctionDefault.py
Replace "method" with "function"
> SONARPY-195 Improve message for CognitiveComplexityFunctionCheck

- sslr-python-toolkit/pom.xml
> SONARPY-283 SSLR Toolkit crashes with ClassNotFoundException at startup

- python-checks/src/main/java/org/sonar/python/checks/XPathCheck.java
- python-checks/src/test/java/org/sonar/python/checks/XPathCheckTest.java
- python-checks/src/test/resources/checks/xpath-print-statement.py
Reverts SonarSource/sonar-python#191
> Revert "SONARPY-289 Improve XPath rule to report on node rather than line"

- python-frontend/src/main/java/org/sonar/python/frontend/PythonKeyword.java
- python-frontend/src/main/java/org/sonar/python/frontend/PythonParser.java
- python-frontend/src/main/java/org/sonar/python/frontend/PythonTokenLocation.java
- python-frontend/src/test/java/org/sonar/python/frontend/PythonKeywordTest.java
- python-frontend/src/test/java/org/sonar/python/frontend/PythonParserTest.java
- python-frontend/src/test/java/org/sonar/python/frontend/PythonTokenLocationTest.java
- python-frontend/test.sh
- sonar-python-plugin/pom.xml
- sonar-python-plugin/src/main/java/org/sonar/plugins/python/PythonHighlighter.java
- sonar-python-plugin/src/main/java/org/sonar/plugins/python/PythonScanner.java
- sonar-python-plugin/src/test/java/org/sonar/plugins/python/PythonHighlighterTest.java
> SONARPY-340 Syntax highlighting based on PyCharm frontend

- python-checks/src/main/java/org/sonar/python/checks/InequalityUsageCheck.java
- python-checks/src/test/resources/checks/longIntegerWithLowercaseSuffix.py
- python-squid/src/main/java/org/sonar/python/api/tree/PyListLiteralTree.java
- python-squid/src/main/java/org/sonar/python/api/tree/PyNumericLiteralTree.java
- python-squid/src/main/java/org/sonar/python/api/tree/PyTreeVisitor.java
- python-squid/src/main/java/org/sonar/python/api/tree/PyUnaryExpressionTree.java
- python-squid/src/main/java/org/sonar/python/api/tree/Tree.java
- python-squid/src/main/java/org/sonar/python/tree/BaseTreeVisitor.java
- python-squid/src/main/java/org/sonar/python/tree/PyBinaryExpressionTreeImpl.java
- python-squid/src/main/java/org/sonar/python/tree/PyListLiteralTreeImpl.java
- python-squid/src/main/java/org/sonar/python/tree/PyNumericLiteralTreeImpl.java
- python-squid/src/main/java/org/sonar/python/tree/PyUnaryExpressionTreeImpl.java
- python-squid/src/main/java/org/sonar/python/tree/PythonTreeMaker.java
- python-squid/src/test/java/org/sonar/python/tree/PythonTreeMakerTest.java
Add support for numeric literal expression
> SONARPY-392 Migrate LongIntegerWithLowercaseSuffixUsage check

- its/ruling/src/test/resources/expected/python-S3827.json
- python-checks-testkit/src/main/java/org/sonar/python/checks/utils/PythonCheckVerifier.java
- python-checks-testkit/src/test/java/org/sonar/python/checks/utils/PythonCheckVerifierTest.java
- python-checks/src/main/java/org/sonar/python/checks/UndeclaredNameUsageCheck.java
- python-checks/src/test/java/org/sonar/python/checks/UndeclaredNameUsageCheckTest.java
- python-checks/src/test/resources/checks/undeclaredNameUsageImported.py
- python-checks/src/test/resources/checks/undeclaredNameUsageWithUnresolvedWildcardImport.py
- python-checks/src/test/resources/checks/undeclaredNameUsageWithWildcardImport.py
- python-frontend/src/main/java/org/sonar/plugins/python/api/PythonVisitorContext.java
- python-frontend/src/main/java/org/sonar/plugins/python/api/tree/ImportFrom.java
- python-frontend/src/main/java/org/sonar/python/TestPythonVisitorRunner.java
- python-frontend/src/main/java/org/sonar/python/semantic/SymbolTableBuilder.java
- python-frontend/src/main/java/org/sonar/python/semantic/SymbolUtils.java
- python-frontend/src/main/java/org/sonar/python/tree/ImportFromImpl.java
- python-frontend/src/test/java/org/sonar/plugins/python/api/PythonVisitorContextTest.java
- python-frontend/src/test/java/org/sonar/python/TestPythonVisitorRunnerTest.java
- python-frontend/src/test/java/org/sonar/python/semantic/ProjectLevelSymbolTableTest.java
- python-frontend/src/test/java/org/sonar/python/semantic/SymbolUtilsTest.java
- sonar-python-plugin/src/main/java/org/sonar/plugins/python/PythonScanner.java
- sonar-python-plugin/src/test/java/org/sonar/plugins/python/PythonSensorTest.java
> SONARPY-535 FN on S3827: Undefined symbols when 'import *' is used

- python-checks/src/main/java/org/sonar/python/checks/ArgumentNumberCheck.java
- python-checks/src/test/resources/checks/argumentNumberWithImport.py
- python-checks/src/test/resources/checks/hotspots/secureCookie.py
- python-frontend/src/main/java/org/sonar/plugins/python/api/symbols/FunctionSymbol.java
- python-frontend/src/main/java/org/sonar/python/semantic/FunctionSymbolImpl.java
- python-frontend/src/main/java/org/sonar/python/semantic/SymbolTableBuilder.java
- python-frontend/src/main/java/org/sonar/python/semantic/SymbolUtils.java
- python-frontend/src/test/java/org/sonar/python/semantic/FunctionSymbolTest.java
> SONARPY-576 Rule S2092: Flask.make_response() and flask.redirect() should have 'Flask.Response' as return type

- python-frontend/src/main/java/org/sonar/python/semantic/ClassSymbolImpl.java
- python-frontend/src/test/java/org/sonar/python/semantic/SymbolUtilsTest.java
Fix a problem detected on pypy: https://github.com/mozillazg/pypy/blob/master/lib-python/2.7/plat-mac/lib-scriptpackages/CodeWarrior/Standard_Suite.py#L14
> Avoid stack overflow on class inheriting from itself

- python-checks/src/main/java/org/sonar/python/checks/RobustCipherAlgorithmCheck.java
- python-checks/src/test/resources/checks/robustCipherAlgorithm.py
Minor fixes after @eric-therond-sonarsource 's review (changes issue messages).
> SONARPY-469 Rule 5547: standardize issue messages

- its/ruling/src/test/resources/expected/python-S905.json
- python-checks/src/main/java/org/sonar/python/checks/UselessStatementCheck.java
- python-checks/src/test/resources/checks/uselessStatement.py
- python-checks/src/test/resources/checks/uselessStatementCustom.py
Please have a look at https://jira.sonarsource.com/browse/SONARPY-667?focusedCommentId=237927&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-237927 which addresses some of the FPs mentionned.
> SONARPY-667 Fix various FPs on rule S905

- python-checks/src/main/java/org/sonar/python/checks/Expressions.java
- python-checks/src/main/java/org/sonar/python/checks/IdentityComparisonWithNewObjectCheck.java
- python-checks/src/test/resources/checks/identityComparisonWithNewObjects.py
Excluded unpacking assignments from singleAssignedValue
> fixed overlap with S5727 and S3403

- pom.xml
To merge after the release of sonar-python 2.12
> SONARPY-723 Update vulnerable dependencies

- python-frontend/src/main/java/org/sonar/python/types/InferredTypes.java
- python-frontend/src/main/java/org/sonar/python/types/RuntimeType.java
- python-frontend/src/test/java/org/sonar/python/types/InferredTypesTest.java
- python-frontend/src/test/java/org/sonar/python/types/RuntimeTypeTest.java
> SONARPY-728 Improve secondary locations for type inference issues

- python-frontend/src/main/java/org/sonar/plugins/python/api/SubscriptionContext.java
- python-frontend/src/main/java/org/sonar/python/SubscriptionVisitor.java
- python-frontend/src/main/java/org/sonar/python/types/TypeShed.java
- python-frontend/src/test/java/org/sonar/python/PythonVisitorCheckTest.java
- python-frontend/src/test/java/org/sonar/python/types/TypeShedTest.java
This reverts commit 7599f2c61a253f05da2ee04413e88bd7d2821f6a.
> Remove API to access symbols generated from stub files

- .gitignore
- .gitmodules
- python-frontend/pom.xml
- python-frontend/src/main/java/org/sonar/python/semantic/FunctionSymbolImpl.java
- python-frontend/src/main/java/org/sonar/python/types/InferredTypes.java
- python-frontend/src/main/protobuf/symbols.proto
- python-frontend/src/main/resources/org/sonar/python/types/protobuf/annoy.protobuf
- python-frontend/src/test/java/org/sonar/python/semantic/ClassSymbolImplTest.java
- python-frontend/src/test/java/org/sonar/python/semantic/FunctionSymbolTest.java
- python-frontend/src/test/java/org/sonar/python/types/InferredTypesTest.java
- python-frontend/typeshed_serializer/README.md
- python-frontend/typeshed_serializer/requirements.txt
- python-frontend/typeshed_serializer/serializer/symbols.py
- python-frontend/typeshed_serializer/serializer/typeshed_serializer.py
- python-frontend/typeshed_serializer/tests/test_typeshed_serializer.py
- python-frontend/typeshed_serializer/tox.ini
Build is failing due to tox not being available yet on Cirrus (SONARPY-873)
> SONARPY-868 Serialize "annoy" library using mypy and protobuf

- python-frontend/src/main/java/org/sonar/plugins/python/api/tree/BaseTreeVisitor.java
- python-frontend/src/main/java/org/sonar/plugins/python/api/tree/DoubleStarPattern.java
- python-frontend/src/main/java/org/sonar/plugins/python/api/tree/KeyValuePattern.java
- python-frontend/src/main/java/org/sonar/plugins/python/api/tree/MappingPattern.java
- python-frontend/src/main/java/org/sonar/plugins/python/api/tree/Tree.java
- python-frontend/src/main/java/org/sonar/plugins/python/api/tree/TreeVisitor.java
- python-frontend/src/main/java/org/sonar/plugins/python/api/tree/ValuePattern.java
- python-frontend/src/main/java/org/sonar/python/api/PythonGrammar.java
- python-frontend/src/main/java/org/sonar/python/tree/DoubleStarPatternImpl.java
- python-frontend/src/main/java/org/sonar/python/tree/KeyValuePatternImpl.java
- python-frontend/src/main/java/org/sonar/python/tree/MappingPatternImpl.java
- python-frontend/src/main/java/org/sonar/python/tree/PythonTreeMaker.java
- python-frontend/src/main/java/org/sonar/python/tree/ValuePatternImpl.java
- python-frontend/src/test/java/org/sonar/python/tree/PythonTreeMakerMatchStatementTest.java
There's an unaddressed issue on Next. I think it's a fair issue that nevertheless can be ignored given the context and I'd normally close it as "Won't fix", but given it comes from DBD, I let you have a look at it first.
> SONARPY-915 Match / case statement: support mapping patterns

- .github/workflows/release.yml
Upgrade the release workflow following https://github.com/SonarSource/gh-action_release/blob/master/README.md
> SONARPY-988 Upgrade the gh-action_release/main GitHub action to version 4

- pom.xml
- python-frontend/typeshed_serializer/requirements.txt
https://github.com/protocolbuffers/protobuf/releases/tag/v21.7
> SONARPY-1200 Update protobuf to version 3.21.7

- python-checks/src/main/java/org/sonar/python/checks/RaiseOutsideExceptCheck.java
- python-checks/src/test/resources/checks/raiseOutsideExcept.py
Slight modification on the rule : add the new kind for except group.
Added a test to expressly test it.
> SONARPY-1179 Update S5747 (RaiseOutsideExceptCheck) to not report an issue inside a 'except*'

- python-checks/src/test/resources/checks/unreachableExcept.py
Seems nothing to be done on the rule side, it's already handling both except and except* without distinction.
I didn't find any specific case to except*.
I added several use case to ensure it is working properly.
> SONARPY-1180 S1045(UnreachableExceptCheck) should report on except*

- its/ruling/src/test/java/org/sonar/python/it/PythonPrAnalysisTest.java
- python-frontend/src/main/java/org/sonar/python/caching/CacheContextImpl.java
- python-frontend/src/test/java/org/sonar/python/caching/CacheContextImplTest.java
- sonar-python-plugin/src/test/java/org/sonar/plugins/python/PythonSensorTest.java
This reverts commit be08db8ea6ea942110c3992ee9b444f439da0e23.
> Re-enable PR analysis caching

- its/plugin/it-python-plugin-test/profiles/profile-python-test-rules.xml
- its/plugin/it-python-plugin-test/projects/test_code/tests/my_other_test_file.py
- its/plugin/it-python-plugin-test/projects/test_code/tests/test_my_code.py
- its/plugin/it-python-plugin-test/projects/test_code/tests/yet_another_test_file.py
- its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/TestRulesTest.java
- its/ruling/src/test/java/org/sonar/python/it/PythonExtendedRulingTest.java
- sonar-python-plugin/src/main/java/org/sonar/plugins/python/indexer/SonarQubePythonIndexer.java
- sonar-python-plugin/src/test/java/org/sonar/plugins/python/PythonSensorTest.java
- sonar-python-plugin/src/test/java/org/sonar/plugins/python/indexer/SonarQubePythonIndexerTest.java
It is worth noting that failing to parse test files will now fail the analysis when `failFast=true`. I don't think this is a big issue, as this is supposed to be an internal property, but this might impact our Peach jobs if some projects contain invalid syntax in their test files. In which case we might want to explicitly exclude parse errors on test files from failing the analysis.
> SONARPY-1247 Fix inconsistencies in test rule results when test dirs are configured

- its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/BanditReportTest.java
- its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/CPDTest.java
- its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/CoverageTest.java
- its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/CustomRulesTest.java
- its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/Flake8ReportTest.java
- its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/MetricsTest.java
- its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/MypyReportTest.java
- its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/NoSonarTest.java
- its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/PylintReportTest.java
- its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/RuffReportTest.java
- its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/TestReportTest.java
- its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/TestRulesTest.java
- its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/TestsUtils.java
- its/ruling/src/test/java/org/sonar/python/it/PythonExtendedRulingTest.java
- its/ruling/src/test/java/org/sonar/python/it/PythonPrAnalysisTest.java
- its/ruling/src/test/java/org/sonar/python/it/PythonRulingTest.java
- its/ruling/src/test/java/org/sonar/python/it/RulingHelper.java
- **SONARPY-1944 Investigate TypeShed failures on CI**
- **Update protobuf**
- **SONARPY-1480 Optimization of plugin download**
- **Same, but for custom-rules-plugin**
- **SONARPY-1946 Update scanner version in QA tests**
> SONARPY-1946 Update scanner version in QA tests

- .github/workflows/releasability.yml
- **New releasability**
- **fix indent**
> SONARPY-2086 Update CI pipeline to use releasability checks V2

- python-frontend/src/main/java/org/sonar/python/api/PythonGrammarBuilder.java
- python-frontend/src/main/java/org/sonar/python/tree/PythonTreeMaker.java
- python-frontend/src/test/java/org/sonar/python/tree/PythonTreeMakerTest.java
- python-frontend/src/test/resources/parser/python/own/set_comprehension.py
The tests pass, but I'm not totally sure that they don't break anything
> SONARPY-1573: Fix parse error of unparenthesized walrus in set literals and comprehension

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/PullRequestClosed.yml
- .github/workflows/PullRequestCreated.yml
- .github/workflows/RequestReview.yml
- .github/workflows/SubmitReview.yml
[SONARPY-2237](https://sonarsource.atlassian.net/browse/SONARPY-2237)
To review:
Make sure the files are the same as these
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestClosed.yml
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestCreated.yml
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/RequestReview.yml
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/SubmitReview.yml
https://raw.githubusercontent.com/SonarSource/sonar-dotnet-enterprise/refs/heads/master/.github/PULL_REQUEST_TEMPLATE.md?token=GHSAT0AAAAAACM3Q6EYDU5DNCGFOFCNBMAYZYSOQXA
Make sure that PullRequestCreated.yml has the correct Jira project on the last line …
> SONARPY-2237 Add Jira integration

- python-frontend/src/main/java/org/sonar/python/semantic/v2/converter/PythonTypeToDescriptorConverter.java
- python-frontend/src/test/java/org/sonar/python/semantic/v2/converter/PythonTypeToDescriptorConverterTest.java
[SONARPY-2256](https://sonarsource.atlassian.net/browse/SONARPY-2256)
Part of 
[SONARPY-2256]: https://sonarsource.atlassian.net/browse/SONARPY-2256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2256 Resolve fully qualified names for class members descriptors

- python-checks/src/test/resources/checks/nonCallableCalled.py
- python-frontend/src/main/java/org/sonar/python/semantic/v2/types/TrivialTypeInferenceVisitor.java
- python-frontend/src/test/java/org/sonar/python/semantic/v2/TypeInferenceV2Test.java
[SONARPY-2250](https://sonarsource.atlassian.net/browse/SONARPY-2250)
[SONARPY-2254](https://sonarsource.atlassian.net/browse/SONARPY-2254)
Part of 
Adds nested classes and static fields to the class type
[SONARPY-2250]: https://sonarsource.atlassian.net/browse/SONARPY-2250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SONARPY-2254]: https://sonarsource.atlassian.net/browse/SONARPY-2254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2250 SONARPY-2254 Need to resolve a type when it is pointing to nested class

- python-frontend/src/main/java/org/sonar/python/semantic/v2/FunctionTypeBuilder.java
- python-frontend/src/main/java/org/sonar/python/semantic/v2/SymbolsModuleTypeProvider.java
- python-frontend/src/main/java/org/sonar/python/semantic/v2/converter/AnyDescriptorToPythonTypeConverter.java
- python-frontend/src/main/java/org/sonar/python/semantic/v2/converter/ConversionContext.java
- python-frontend/src/main/java/org/sonar/python/semantic/v2/converter/FunctionDescriptorToPythonTypeConverter.java
- python-frontend/src/main/java/org/sonar/python/types/v2/FunctionType.java
- python-frontend/src/test/java/org/sonar/python/semantic/v2/ProjectLevelTypeTableTest.java
- python-frontend/src/test/java/org/sonar/python/semantic/v2/TypeInferenceV2Test.java
- python-frontend/src/test/java/org/sonar/python/semantic/v2/converter/ConversionContextTest.java
- python-frontend/src/test/java/org/sonar/python/semantic/v2/converter/DescriptorToPythonTypeConverterTest.java
[SONARPY-1772](https://sonarsource.atlassian.net/browse/SONARPY-1772)
[SONARPY-1772]: https://sonarsource.atlassian.net/browse/SONARPY-1772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-1772 Represent decorators in FunctionType

- .github/workflows/PullRequestCreated.yml
[SONARPY-2294](https://sonarsource.atlassian.net/browse/SONARPY-2294)
[SONARPY-2294]: https://sonarsource.atlassian.net/browse/SONARPY-2294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2294 Update Jira automation to avoid creation of unwanted tickets

- python-frontend/src/main/java/org/sonar/python/semantic/v2/types/Propagation.java
[SONARPY-2296](https://sonarsource.atlassian.net/browse/SONARPY-2296)
[SONARPY-2296]: https://sonarsource.atlassian.net/browse/SONARPY-2296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2296 Fix remaining quality issue

- python-frontend/src/test/java/org/sonar/python/semantic/v2/converter/PythonTypeToDescriptorConverterTest.java
[SONARPY-2290](https://sonarsource.atlassian.net/browse/SONARPY-2290)
[SONARPY-2290]: https://sonarsource.atlassian.net/browse/SONARPY-2290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2290 changes of existing unit tests with assertions on the function decorators support

- its/ruling/src/test/resources/expected/python-S3752.json
[SONARPY-2189](https://sonarsource.atlassian.net/browse/SONARPY-2189)
[SONARPY-2189]: https://sonarsource.atlassian.net/browse/SONARPY-2189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2189 Update ruling expectations

- python-frontend/src/test/java/org/sonar/python/semantic/v2/ProjectLevelTypeTableTest.java
[SONARPY-2290](https://sonarsource.atlassian.net/browse/SONARPY-2290)
[SONARPY-2290]: https://sonarsource.atlassian.net/browse/SONARPY-2290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2290 re enable tests

- python-checks/src/test/resources/checks/unusedFunctionParameter/unusedFunctionParameter.py
[SONARPY-2289](https://sonarsource.atlassian.net/browse/SONARPY-2289)
[SONARPY-2289]: https://sonarsource.atlassian.net/browse/SONARPY-2289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2289 Add tests that document FPs that are not raised by S1172 

- python-frontend/src/main/java/org/sonar/python/index/FunctionDescriptor.java
- python-frontend/src/main/java/org/sonar/python/semantic/v2/FunctionTypeBuilder.java
[SONARPY-2338](https://sonarsource.atlassian.net/browse/SONARPY-2338)
Part of 
[SONARPY-2338]: https://sonarsource.atlassian.net/browse/SONARPY-2338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2338 Fix quality gate issues

- python-frontend/src/test/java/org/sonar/python/tree/PythonTreeMakerTest.java
- python-frontend/src/test/resources/parser/python/own/python313.py
[SONARPY-2340](https://sonarsource.atlassian.net/browse/SONARPY-2340)
[SONARPY-2340]: https://sonarsource.atlassian.net/browse/SONARPY-2340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2340 add Python 3.13 examples to the parser test

- its/plugin/it-python-plugin-test/pom.xml
- its/plugin/pom.xml
- its/plugin/python-custom-rules-plugin/pom.xml
- its/pom.xml
- its/ruling/pom.xml
- pom.xml
- python-checks-testkit/pom.xml
- python-checks/pom.xml
- python-frontend/pom.xml
- sonar-python-plugin/pom.xml
[SONARPY-2375](https://sonarsource.atlassian.net/browse/SONARPY-2375)
[SONARPY-2375]: https://sonarsource.atlassian.net/browse/SONARPY-2375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2375 Prepare for next development iteration

- python-frontend/src/main/java/org/sonar/python/semantic/v2/TypeInferenceV2.java
- python-frontend/src/main/java/org/sonar/python/semantic/v2/types/Assignment.java
- python-frontend/src/main/java/org/sonar/python/semantic/v2/types/AstBasedPropagation.java
- python-frontend/src/main/java/org/sonar/python/semantic/v2/types/AstBasedTypeInference.java
- python-frontend/src/main/java/org/sonar/python/semantic/v2/types/Definition.java
- python-frontend/src/main/java/org/sonar/python/semantic/v2/types/FlowSensitiveTypeInference.java
- python-frontend/src/main/java/org/sonar/python/semantic/v2/types/LoopAssignment.java
- python-frontend/src/main/java/org/sonar/python/semantic/v2/types/ParameterDefinition.java
- python-frontend/src/main/java/org/sonar/python/semantic/v2/types/ProgramStateTypeInferenceVisitor.java
- python-frontend/src/main/java/org/sonar/python/semantic/v2/types/Propagation.java
- python-frontend/src/main/java/org/sonar/python/semantic/v2/types/PropagationVisitor.java
- python-frontend/src/main/java/org/sonar/python/semantic/v2/types/TrivialTypeInferenceVisitor.java
- python-frontend/src/main/java/org/sonar/python/semantic/v2/types/TrivialTypePropagationVisitor.java
- python-frontend/src/main/java/org/sonar/python/tree/ParenthesizedExpressionImpl.java
- python-frontend/src/main/java/org/sonar/python/tree/UnaryExpressionImpl.java
- python-frontend/src/main/java/org/sonar/python/types/v2/TypeUtils.java
- python-frontend/src/test/java/org/sonar/python/semantic/v2/TypeInferenceV2Test.java
- python-frontend/src/test/java/org/sonar/python/semantic/v2/types/TrivialTypePropagationVisitorTest.java
- python-frontend/src/test/java/org/sonar/python/types/v2/TypesTestUtils.java
[SONARPY-2257](https://sonarsource.atlassian.net/browse/SONARPY-2257)
[SONARPY-2257]: https://sonarsource.atlassian.net/browse/SONARPY-2257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2257 Ensure that the type of unary expressions of non-literals propagate

- python-frontend/src/main/java/org/sonar/python/semantic/v2/types/AstBasedTypeInference.java
- python-frontend/src/main/java/org/sonar/python/semantic/v2/types/TrivialTypePropagationVisitor.java
- python-frontend/src/test/java/org/sonar/python/semantic/v2/types/TrivialTypePropagationVisitorTest.java
[SONARPY-2378](https://sonarsource.atlassian.net/browse/SONARPY-2378)
[SONARPY-2378]: https://sonarsource.atlassian.net/browse/SONARPY-2378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2378 Fix license

- docs/LICENSE.txt
- docs/pom.xml
- docs/python-custom-rule-examples/pom.xml
- docs/python-custom-rule-examples/src/main/java/org/sonar/samples/python/CustomPythonRuleRepository.java
- docs/python-custom-rule-examples/src/main/java/org/sonar/samples/python/CustomPythonRulesPlugin.java
- docs/python-custom-rule-examples/src/main/java/org/sonar/samples/python/checks/CustomPythonSubscriptionCheck.java
- docs/python-custom-rule-examples/src/main/java/org/sonar/samples/python/checks/CustomPythonVisitorCheck.java
- docs/python-custom-rule-examples/src/main/java/org/sonar/samples/python/checks/package-info.java
- docs/python-custom-rule-examples/src/main/java/org/sonar/samples/python/package-info.java
- docs/python-custom-rule-examples/src/main/resources/license-header.txt
- docs/python-custom-rule-examples/src/main/resources/org/sonar/l10n/python/rules/python/subscription.html
- docs/python-custom-rule-examples/src/main/resources/org/sonar/l10n/python/rules/python/visitor.html
- docs/python-custom-rule-examples/src/test/java/org/sonar/samples/python/CustomPythonRuleRepositoryTest.java
- docs/python-custom-rule-examples/src/test/java/org/sonar/samples/python/CustomPythonRulesPluginTest.java
- docs/python-custom-rule-examples/src/test/java/org/sonar/samples/python/checks/CustomPythonSubscriptionCheckTest.java
- docs/python-custom-rule-examples/src/test/java/org/sonar/samples/python/checks/CustomPythonVisitorCheckTest.java
- docs/python-custom-rule-examples/src/test/resources/checks/customPythonSubscriptionCheck.py
- docs/python-custom-rule-examples/src/test/resources/checks/customPythonVisitorCheck.py
- pom.xml
[SONARPY-2371](https://sonarsource.atlassian.net/browse/SONARPY-2371)
[SONARPY-2371]: https://sonarsource.atlassian.net/browse/SONARPY-2371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2371 Move the custom rule examples to sonar-python repository

- renovate.json
[SONARPY-2393](https://sonarsource.atlassian.net/browse/SONARPY-2393)
[SONARPY-2393]: https://sonarsource.atlassian.net/browse/SONARPY-2393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2393 Disable the pinning of GHA digests

- python-frontend/src/main/java/org/sonar/plugins/python/package-info.java
[SONARPY-2404](https://sonarsource.atlassian.net/browse/SONARPY-2404)
Part of 
[SONARPY-2404]: https://sonarsource.atlassian.net/browse/SONARPY-2404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2404 Add package-info to org.sonar.plugins.python

- .github/workflows/PullRequestCreated.yml
[SONARPY-2401](https://sonarsource.atlassian.net/browse/SONARPY-2401)
[SONARPY-2401]: https://sonarsource.atlassian.net/browse/SONARPY-2401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2401 Disable JIRA automation for Renovate

- .github/workflows/PullRequestCreated.yml
Evidence of it working: https://github.com/SonarSource/sonar-python/actions/runs/12161701798
Before: https://github.com/SonarSource/sonar-python/pull/2212
I found the issue through [ActionLint](https://rhysd.github.io/actionlint/#eJyVU2Fv2jAQ/c6vuHZTKVOTSNu3TEilG1vbaQGFVtU0TZFJDkgxdmafwxDlv89OIKPqmFi+RPb5vXv3ni3YAkMYGs4hxp8GNcEHhYwwa7WkCFsAha0lqq65NQCtCtQhfD+VBQrMTn+0Wo9yrF3REW15tjSJLdUwcbiVKysjtGdbghkbQcbjtqKpKhWoFrnWuRS6pgLIM4/kHO3xpcoJq91X8EkqwF+ESjAOw/gCKE/nSKBn0vAMxghp3REWTBjG+aoC5pMQnrbEANOcZmbsY4mC/P3p/RmyzFdYSH/itt1A0O3uAK6gc5Jq1VCdnT1n0ygyVL4zEE660L6S1N4//Hq9hhNNTJF+sLjzw1IoJ44X0I4G3u1N3Gt3jqBx8i3BxMIUCllaI4J2BzabF9hUCmK50P8QwNkYufbf+M4Fy5hh4YYTaY76D6kmLJrMPJtaCBptBqSbnka7yzSSgqmRNCrFoGSGk8dSsoF7S8UKm/9l+a5BLK2osFnBjnE/Q/dlVjWXxcJKD+o5gurKBOu4Pxwkg4eoHydR72s/+dgbXW+8x1wxqE7AE3y+ub …
> SONARPY-2411 Fix JIRA automation triggered by Renovate

- python-frontend/src/main/java/org/sonar/python/semantic/v2/converter/AmbiguousDescriptorToPythonTypeConverter.java
- python-frontend/src/main/java/org/sonar/python/semantic/v2/types/ProgramStateTypeInferenceVisitor.java
- python-frontend/src/main/java/org/sonar/python/types/v2/LazyUnionType.java
- python-frontend/src/main/java/org/sonar/python/types/v2/TypeUtils.java
- python-frontend/src/main/java/org/sonar/python/types/v2/UnionType.java
- python-frontend/src/test/java/org/sonar/python/semantic/v2/TypeInferenceV2Test.java
- python-frontend/src/test/java/org/sonar/python/semantic/v2/converter/PythonTypeToDescriptorConverterTest.java
- python-frontend/src/test/java/org/sonar/python/types/v2/UnionTypeTest.java
[SONARPY-2235](https://sonarsource.atlassian.net/browse/SONARPY-2235)
[SONARPY-2235]: https://sonarsource.atlassian.net/browse/SONARPY-2235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2235: UnionType creation should have more guards

- python-frontend/src/main/java/org/sonar/python/tree/TreeUtils.java
[SONARPY-2435](https://sonarsource.atlassian.net/browse/SONARPY-2435)
[SONARPY-2435]: https://sonarsource.atlassian.net/browse/SONARPY-2435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2435 Fix broken build after merging

- docs/pom.xml
- docs/python-custom-rules-example/pom.xml
- its/plugin/it-python-plugin-test/pom.xml
- its/plugin/pom.xml
- its/plugin/python-custom-rules-plugin/pom.xml
- its/pom.xml
- its/ruling/pom.xml
- pom.xml
- python-checks-testkit/pom.xml
- python-checks/pom.xml
- python-frontend/pom.xml
- sonar-python-plugin/pom.xml
[SONARPY-2446](https://sonarsource.atlassian.net/browse/SONARPY-2446)
[SONARPY-2446]: https://sonarsource.atlassian.net/browse/SONARPY-2446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2446 Prepare for next development iteration

- its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/TestsUtils.java
- its/ruling/src/test/java/org/sonar/python/it/RulingHelper.java
[SONARPY-2454](https://sonarsource.atlassian.net/browse/SONARPY-2454)
[SONARPY-2454]: https://sonarsource.atlassian.net/browse/SONARPY-2454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2454 Disable telemetry in the ITs

- its/plugin/it-python-plugin-test/src/test/java/com/sonar/python/it/plugin/MetricsTest.java
[SONARPY-2466](https://sonarsource.atlassian.net/browse/SONARPY-2466)
[SONARPY-2466]: https://sonarsource.atlassian.net/browse/SONARPY-2466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2466 Remove unused code

- python-checks/src/main/java/org/sonar/python/checks/IgnoredPureOperationsCheck.java
[SONARPY-2468](https://sonarsource.atlassian.net/browse/SONARPY-2468)
[SONARPY-2468]: https://sonarsource.atlassian.net/browse/SONARPY-2468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2468 IgnoredPureOperationsCheck#checkExpression should reuse TypeCheckers

- .cirrus.yml
[SONARPY-2469](https://sonarsource.atlassian.net/browse/SONARPY-2469)
Part of SONARPY-2425
[SONARPY-2469]: https://sonarsource.atlassian.net/browse/SONARPY-2469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2469 Remove build dependency from win build

- .cirrus.yml
[SONARPY-2472](https://sonarsource.atlassian.net/browse/SONARPY-2472)
[SONARPY-2472]: https://sonarsource.atlassian.net/browse/SONARPY-2472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2473 Optimize Windows build by using a bigger instance and parallel submodule fetching

- .cirrus.yml
[SONARPY-2476](https://sonarsource.atlassian.net/browse/SONARPY-2476)
[SONARPY-2476]: https://sonarsource.atlassian.net/browse/SONARPY-2476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2476: General performance tuning

- its/ruling/src/test/java/org/sonar/python/it/PythonRulingTest.java
- its/ruling/src/test/java/org/sonar/python/it/TestDurationMeasureExtension.java
[SONARPY-2456](https://sonarsource.atlassian.net/browse/SONARPY-2456)
[SONARPY-2456]: https://sonarsource.atlassian.net/browse/SONARPY-2456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2456: Collect how long each ruling project took to analyze

- python-checks/src/main/resources/org/sonar/l10n/py/rules/python/S6554.html
- python-checks/src/main/resources/org/sonar/l10n/py/rules/python/S6662.html
- python-checks/src/main/resources/org/sonar/l10n/py/rules/python/S6663.html
- python-checks/src/main/resources/org/sonar/l10n/py/rules/python/S6984.html
- sonarpedia.json
[SONARPY-2445](https://sonarsource.atlassian.net/browse/SONARPY-2445)
[SONARPY-2445]: https://sonarsource.atlassian.net/browse/SONARPY-2445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2445 Update rule metadata

- .cirrus.yml
[SONARPY-2432](https://sonarsource.atlassian.net/browse/SONARPY-2432)
[SONARPY-2432]: https://sonarsource.atlassian.net/browse/SONARPY-2432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Revert SONARPY-2432

- docs/pom.xml
- docs/python-custom-rules-example/pom.xml
- its/plugin/it-python-plugin-test/pom.xml
- its/plugin/pom.xml
- its/plugin/python-custom-rules-plugin/pom.xml
- its/pom.xml
- its/ruling/pom.xml
- pom.xml
- python-checks-testkit/pom.xml
- python-checks/pom.xml
- python-frontend/pom.xml
- sonar-python-plugin/pom.xml
[SONARPY-2483](https://sonarsource.atlassian.net/browse/SONARPY-2483)
[SONARPY-2483]: https://sonarsource.atlassian.net/browse/SONARPY-2483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2483 Prepare for next development iteration

- .mailmap
- pom.xml
[SONARPY-2484](https://sonarsource.atlassian.net/browse/SONARPY-2484)
[SONARPY-2484]: https://sonarsource.atlassian.net/browse/SONARPY-2484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2484 Update contributors to the project
